version: "2"
services:

  spring-api-gateway:
    image: gateway-api:1.0
    build: spring-api-gateway/
    restart: always
    network_mode: host
    depends_on:
      - spring-eureka-server
    ports:
      - 8050:8050
    expose:
      - 8050

  spring-track-service:
    image: track-service:1.0
    build: spring-track-service/
    restart: always
    network_mode: host
    depends_on:
      - spring-eureka-server
    ports:
      - 8080:8080
    expose:
      - 8080

  spring-user-service:
    image: user-service:1.0
    build: spring-user-service/
    restart: always
    network_mode: host
    depends_on:
      - spring-eureka-server
    ports:
      - 8060:8060
    expose:
      - 8060


  spring-eureka-server:
    image: eureka-server:1.0
    build: spring-eureka-server/
    restart: always
    network_mode: host
    depends_on:
      - spring-config-server
    ports:
      - 8761:8761
    expose:
      - 8761

  spring-config-server:
    image: config-server:1.0
    build: spring-config-server/
    restart: always
    network_mode: host
    ports:
      - 8880:8880
    expose:
      - 8880

  mongo:
    image: mongo:4.1
    ports:
      - 27017:27017
    expose:
      - 27017


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
